blank_issues_enabled: false
contact_links:
  - name: Документация arm_info
    url: https://newmishka.gitbook.io/newmishka-docs/
    about: Перед созданием Issue проверьте руководство и раздел решения проблем.
